#!/usr/bin/env bash
#
# run_cluster_seed.sh -- rerun the DEFAULT (un-normalized) pipeline with a
# different permutation seed, into a separate results folder, to measure the
# Monte-Carlo noise floor of the FDR-significant calls at n_perms.
#
# The observed scoring is seed-independent and deterministic; only the
# permutation null changes with the seed. Comparing results/ (seed 42) against
# results_seed<N>/ (seed N) with compare_default_vs_qnorm.py gives the bin-set
# Jaccard attributable purely to permutation sampling -- the floor against which
# the normalization-robustness Jaccards should be read.
#
#   bash workflow/run_cluster_seed.sh --seed 7              # core path (no Hi-C)
#   bash workflow/run_cluster_seed.sh --seed 7 --full       # full pipeline
#   bash workflow/run_cluster_seed.sh --seed 7 --dry        # dry run only
#   bash workflow/run_cluster_seed.sh --seed 7 --n-perms 10 # pin perm depth (default 10)
#
# Derives its config from the live base config (overriding ONLY outdir + seed),
# so it can never drift. NOTE: this re-runs scoring deterministically (same
# result as results/), which costs cluster time; it is a one-time supplementary
# check, so simplicity/robustness is preferred over reusing the scored qcats.
# ASCII-only.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BASE_CONFIG="$REPO/workflow/config/config.yaml"
PROFILE="$REPO/workflow/profiles/slurm"

SEED=""
NPERMS=10
FULL=0
DRY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --seed) SEED="$2"; shift 2 ;;
    --seed=*) SEED="${1#*=}"; shift ;;
    --n-perms) NPERMS="$2"; shift 2 ;;
    --n-perms=*) NPERMS="${1#*=}"; shift ;;
    --full) FULL=1; shift ;;
    --dry)  DRY=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
if [ -z "$SEED" ]; then echo "ERROR: --seed <N> is required" >&2; exit 2; fi
case "$SEED" in (*[!0-9]*) echo "ERROR: --seed must be an integer" >&2; exit 2 ;; esac
case "$NPERMS" in (*[!0-9]*) echo "ERROR: --n-perms must be an integer" >&2; exit 2 ;; esac

DERIVED_CONFIG="$REPO/workflow/config/config_seed${SEED}.generated.yaml"
python3 - "$BASE_CONFIG" "$DERIVED_CONFIG" "$SEED" "$NPERMS" << 'PY'
import sys, yaml
base_path, out_path, seed, nperms = sys.argv[1:5]
with open(base_path) as fh:
    cfg = yaml.safe_load(fh)
base_out = cfg.get("outdir", "results")
cfg["outdir"] = "%s_seed%s" % (base_out, seed)
cfg["seed"] = int(seed)
# Pin this arm's permutation depth independently of the base config (which may
# sit at the n_perms=100 production value); robustness arms default to 10 unless
# --n-perms overrides.
cfg["n_perms"] = int(nperms)
# keep normalization OFF (same as the default/production run) so the ONLY
# moving part vs results/ is the permutation seed.
cfg["cohort_reference"] = False
cfg["normalize"] = cfg.get("normalize", "")
header = ("# AUTO-GENERATED by run_cluster_seed.sh from %s.\n"
          "# Differs from the base config ONLY in: outdir, seed, n_perms.\n" % base_path)
with open(out_path, "w") as fh:
    fh.write(header); yaml.safe_dump(cfg, fh, default_flow_style=False, sort_keys=False)
print("  base outdir : %s" % base_out)
print("  seed outdir : %s" % cfg["outdir"])
print("  seed        : %s (was %s)" % (cfg["seed"], yaml.safe_load(open(base_path)).get("seed")))
print("  n_perms     : %s (base was %s)" % (cfg["n_perms"], yaml.safe_load(open(base_path)).get("n_perms")))
PY

CONFIG="$DERIVED_CONFIG"
OUT=$(python3 -c "import yaml;print(yaml.safe_load(open('$CONFIG'))['outdir'])")
echo "== Seed run -> $OUT =="; echo

echo "== Preflight =="
python3 "$REPO/workflow/preflight.py" --configfile "$CONFIG" --core-only
echo

# The p-value layers are needed to compare call sets AND per-sample calibration;
# core-only by default (no Hi-C/figures).
SM_TARGETS=("$REPO/workflow/$OUT/pvalue.done"
            "$REPO/workflow/$OUT/pvalue_samples.done"
            "$REPO/workflow/$OUT/regional/cbe_point_query.tsv"
            "$REPO/workflow/$OUT/regional/cbe_track_changes.tsv"
            "$REPO/workflow/$OUT/regional/agr_track_changes.tsv")
[ "$FULL" = "1" ] && SM_TARGETS=()

echo "== Dry run =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" -n "${SM_TARGETS[@]}"
if [ "$DRY" = "1" ]; then echo; echo "Dry run only."; exit 0; fi

echo; echo "== Submitting to SLURM =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" \
  --rerun-triggers mtime params \
  --profile "$PROFILE" "${SM_TARGETS[@]}"

echo; echo "Done -> workflow/$OUT/. Compare against the default run:"
echo "  python compare_default_vs_qnorm.py \\"
echo "    --default-dir workflow/results/pvalue \\"
echo "    --qnorm-dir   workflow/$OUT/pvalue"
echo "(here the 'qnorm-dir' is the seed run; the Jaccard it reports is the"
echo " permutation-noise floor, NOT a normalization effect.)"
