#!/usr/bin/env bash
# ----------------------------------------------------------------------
# File     : workflow/run_cluster_prior.sh
# Version  : 1.0.0
# Date     : 2026-09-28
# Authors  : Katharina E. Hayer (katharinaehayer@gmail.com) and Claude
#            (Anthropic), co-created
# ----------------------------------------------------------------------
#
# run_cluster_prior.sh -- rerun the DEFAULT pipeline with the composition prior
# (bigwig_to_qcat.py --prior-strength ALPHA) into its own results folder.
#
# WHY: the production per-bin differential calls are floor crossings (one
# condition just under min_signal in both replicates -> score 0; the other just
# above, in one track -> score at the single-track ceiling log2(1/Q_i)). The
# prior shrinks each bin's composition toward Q, P = (x + ALPHA*Q)/(sum x + ALPHA),
# so barely-detectable bins score near 0 and the cliff disappears, while bins
# with real signal keep their composition.
#
# min_signal stays at the BASE value (0.1) by default: with the prior on, a bin
# just under the floor would only have scored ~ its total signal anyway (far
# below the 0.5 differential testing floor), so the hard floor no longer creates
# a cliff -- and keeping it preserves the production sparsity, so `compare` does
# not hit the min_signal=0.01 OOM (see run_cluster_minsig.sh).
#
# Varies ONLY prior_strength (+ outdir, n_perms). Scores observed AND permutation
# qcats with the same ALPHA; score_provenance checks it.
#
#   bash workflow/run_cluster_prior.sh --alpha 1              # scout, n_perms 10
#   bash workflow/run_cluster_prior.sh --alpha 0.5 --dry
#   for a in 0.1 0.5 1 2; do bash workflow/run_cluster_prior.sh --alpha $a; done
#   bash workflow/run_cluster_prior.sh --alpha 1 --n-perms 100   # publishable
#
# ASCII-only.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BASE_CONFIG="$REPO/workflow/config/config.yaml"
PROFILE="$REPO/workflow/profiles/slurm"

ALPHA=""
NPERMS=10
MINSIG=""
DRY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --alpha) ALPHA="$2"; shift 2 ;;
    --alpha=*) ALPHA="${1#*=}"; shift ;;
    --n-perms) NPERMS="$2"; shift 2 ;;
    --n-perms=*) NPERMS="${1#*=}"; shift ;;
    --min-signal) MINSIG="$2"; shift 2 ;;
    --min-signal=*) MINSIG="${1#*=}"; shift ;;
    --dry) DRY=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
[ -z "$ALPHA" ] && { echo "ERROR: --alpha <value> is required" >&2; exit 2; }
case "$ALPHA"  in (*[!0-9.]*|.|"") echo "ERROR: --alpha must be a positive number" >&2; exit 2 ;; esac
case "$NPERMS" in (*[!0-9]*) echo "ERROR: --n-perms must be an integer" >&2; exit 2 ;; esac
if [ -n "$MINSIG" ]; then
  case "$MINSIG" in (*[!0-9.]*|.) echo "ERROR: --min-signal must be a number" >&2; exit 2 ;; esac
fi

TAG="${ALPHA//./p}"
DERIVED_CONFIG="$REPO/workflow/config/config_prior${TAG}.generated.yaml"

python3 - "$BASE_CONFIG" "$DERIVED_CONFIG" "$ALPHA" "$NPERMS" "$MINSIG" << 'PY'
import sys, yaml
base_path, out_path, alpha, nperms, minsig = sys.argv[1:6]
with open(base_path) as fh:
    cfg = yaml.safe_load(fh)
if float(alpha) <= 0:
    sys.exit("ERROR: --alpha must be > 0")
base_out = cfg.get("outdir", "results")
cfg["outdir"] = "%s_prior%s" % (base_out, alpha.replace(".", "p"))
cfg["prior_strength"] = float(alpha)
cfg["n_perms"] = int(nperms)
if minsig:
    cfg["min_signal"] = float(minsig)
    cfg["adaptive_min_signal"] = float(minsig)
cfg["cohort_reference"] = False
cfg["normalize"] = cfg.get("normalize", "")
header = ("# AUTO-GENERATED by run_cluster_prior.sh from %s.\n"
          "# Differs from the base config ONLY in: outdir, prior_strength, n_perms"
          "%s.\n" % (base_path, ", min_signal" if minsig else ""))
with open(out_path, "w") as fh:
    fh.write(header); yaml.safe_dump(cfg, fh, default_flow_style=False, sort_keys=False)
print("  outdir        : %s" % cfg["outdir"])
print("  prior_strength: %s" % cfg["prior_strength"])
print("  min_signal    : %s" % cfg.get("min_signal"))
print("  n_perms       : %s" % cfg["n_perms"])
PY

CONFIG="$DERIVED_CONFIG"
OUT=$(python3 -c "import yaml;print(yaml.safe_load(open('$CONFIG'))['outdir'])")
echo "== prior run -> $OUT =="; echo

echo "== Preflight =="
python3 "$REPO/workflow/preflight.py" --configfile "$CONFIG" --core-only
echo

# Differential p-values are the readout here (they are what the floor
# crossings corrupted), plus the per-sample p-values.
SM_TARGETS=("$REPO/workflow/$OUT/pvalue.done"
            "$REPO/workflow/$OUT/pvalue_samples.done")

echo "== Dry run =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" -n "${SM_TARGETS[@]}"
if [ "$DRY" = "1" ]; then echo; echo "Dry run only."; exit 0; fi

echo; echo "== Submitting to SLURM =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" \
  --rerun-triggers mtime params \
  --profile "$PROFILE" "${SM_TARGETS[@]}"

echo; echo "Done -> workflow/$OUT/."
echo "READOUT (from workflow/):"
echo "  for B in DP EbKO ProB S3T3; do python ../dev/replicate_swap_null.py \\"
echo "    --sheet $OUT/samples.qcat.tsv --cond-a DN --cond-b \$B --min-signal 0.5 \\"
echo "    --prod-stats $OUT/pvalue/diff_DN_vs_\$B.stats.tsv --regions ../regions_manuscript.tsv \\"
echo "    --out-prefix $OUT/swapnull/DN_vs_\${B}_genome; done"
echo "  then count BH hits and floor crossings exactly as for results_seed42."
