#!/usr/bin/env bash
#
# run_cluster_adaptive.sh -- run the pipeline with opt-in adaptive (variable-
# width, equal-coverage) binning into a separate results folder, as an
# alternative-binning arm alongside the fixed 200 bp default run.
#
# Derives its config from the live base config, overriding ONLY outdir +
# adaptive_binning=true (and carrying the adaptive_* params). A single consensus
# segmentation BED is built once (main chromosomes only) and every sample AND the
# permutation null are scored on it, so the differential stays defined on a
# shared grid. Normalization/score-method stay whatever the base config uses.
#
#   bash workflow/run_cluster_adaptive.sh            # core path -> results_adaptive/
#   bash workflow/run_cluster_adaptive.sh --full     # full pipeline
#   bash workflow/run_cluster_adaptive.sh --dry      # dry run only
#
# Compare against the default (fixed-grid) run. The grids are NOT bin-aligned, so
# use the region-overlap comparison (see compare_adaptive_vs_default.py), not the
# bin-for-bin compare_default_vs_qnorm.py. Restrict the default side to main
# chromosomes when comparing (the adaptive grid is main-chrom only).
# ASCII-only.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BASE_CONFIG="$REPO/workflow/config/config.yaml"
PROFILE="$REPO/workflow/profiles/slurm"

FULL=0
DRY=0
NPERMS=10
while [ $# -gt 0 ]; do
  case "$1" in
    --full) FULL=1; shift ;;
    --dry)  DRY=1; shift ;;
    --n-perms) NPERMS="$2"; shift 2 ;;
    --n-perms=*) NPERMS="${1#*=}"; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
case "$NPERMS" in (*[!0-9]*) echo "ERROR: --n-perms must be an integer" >&2; exit 2 ;; esac

DERIVED_CONFIG="$REPO/workflow/config/config_adaptive.generated.yaml"
python3 - "$BASE_CONFIG" "$DERIVED_CONFIG" "$NPERMS" << 'PY'
import sys, yaml
base_path, out_path, nperms = sys.argv[1:4]
with open(base_path) as fh:
    cfg = yaml.safe_load(fh)
base_out = cfg.get("outdir", "results")
cfg["outdir"] = "%s_adaptive" % base_out
cfg["adaptive_binning"] = True
cfg.setdefault("adaptive_fine_bp", 50)
cfg.setdefault("adaptive_min_signal", 0.1)
cfg.setdefault("adaptive_target_bins", 2000000)
cfg["n_perms"] = int(nperms)
header = ("# AUTO-GENERATED by run_cluster_adaptive.sh from %s.\n"
          "# Differs from the base config in: outdir, adaptive_binning=true,\n"
          "# adaptive_fine_bp/min_signal/target_bins, n_perms.\n" % base_path)
with open(out_path, "w") as fh:
    fh.write(header); yaml.safe_dump(cfg, fh, default_flow_style=False, sort_keys=False)
print("  base outdir       : %s" % base_out)
print("  adaptive outdir   : %s" % cfg["outdir"])
print("  n_perms           : %s (base was %s)" % (cfg["n_perms"], yaml.safe_load(open(base_path)).get("n_perms")))
print("  fine_bp/min/target: %s / %s / %s"
      % (cfg["adaptive_fine_bp"], cfg["adaptive_min_signal"], cfg["adaptive_target_bins"]))
PY

CONFIG="$DERIVED_CONFIG"
OUT=$(python3 -c "import yaml;print(yaml.safe_load(open('$CONFIG'))['outdir'])")
echo "== Adaptive-binning run -> $OUT =="; echo

echo "== Preflight =="
python3 "$REPO/workflow/preflight.py" --configfile "$CONFIG" --core-only
echo

SM_TARGETS=("$REPO/workflow/$OUT/pvalue.done"
            "$REPO/workflow/$OUT/pvalue_samples.done"
            "$REPO/workflow/$OUT/regional/cbe_point_query.tsv"
            "$REPO/workflow/$OUT/regional/cbe_track_changes.tsv"
            "$REPO/workflow/$OUT/regional/agr_track_changes.tsv")
[ "$FULL" = "1" ] && SM_TARGETS=()

echo "== Dry run =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" -n "${SM_TARGETS[@]}"
if [ "$DRY" = "1" ]; then echo; echo "Dry run only."; exit 0; fi

echo; echo "== Submitting to SLURM =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" \
  --rerun-triggers mtime params \
  --profile "$PROFILE" "${SM_TARGETS[@]}"

echo; echo "Done -> workflow/$OUT/. Compare against the default (fixed-grid) run:"
echo "  python compare_adaptive_vs_default.py \\"
echo "    --default-dir workflow/results/pvalue \\"
echo "    --adaptive-dir workflow/$OUT/pvalue"
