#!/usr/bin/env bash
#
# run_cluster_minsig.sh -- rerun the DEFAULT (un-normalized) pipeline at a
# different min_signal threshold, into a separate results folder, to test
# whether the regional findings and the within-condition FDR calibration are
# sensitive to the low-signal threshold. Answers the reviewer question
# "why min_signal = 0.1 and not the software default 0.01?".
#
# Varies ONLY min_signal (and outdir/n_perms). Everything else -- seed 42,
# normalization off, track set -- stays at production defaults, so the only
# moving part vs results/ is the threshold. This is the ONE robustness axis to
# add for min_signal; do NOT cross it with seed444/jsd/qnorm (one axis each).
#
#   bash workflow/run_cluster_minsig.sh                      # 0.01, n_perms 10 (scout)
#   bash workflow/run_cluster_minsig.sh --min-signal 0.01    # explicit
#   bash workflow/run_cluster_minsig.sh --min-signal 0.01 --n-perms 100   # publishable
#   bash workflow/run_cluster_minsig.sh --dry                # dry run only
#
# Scout first at n_perms=10 to see DIRECTION (does calibration stay ~0 BH-sig,
# do the regional findings hold?). Promote to n_perms=100 only if it holds.
#
# Derives its config from the live base config (overriding ONLY outdir +
# min_signal + n_perms), so it can never drift. Re-scores fresh into the new
# outdir (min_signal changes scoring), which costs cluster time. ASCII-only.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BASE_CONFIG="$REPO/workflow/config/config.yaml"
PROFILE="$REPO/workflow/profiles/slurm"

MINSIG="0.01"
NPERMS=10
FULL=0
DRY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --min-signal) MINSIG="$2"; shift 2 ;;
    --min-signal=*) MINSIG="${1#*=}"; shift ;;
    --n-perms) NPERMS="$2"; shift 2 ;;
    --n-perms=*) NPERMS="${1#*=}"; shift ;;
    --full) FULL=1; shift ;;
    --dry)  DRY=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
case "$MINSIG" in (*[!0-9.]*|.|"") echo "ERROR: --min-signal must be a number" >&2; exit 2 ;; esac
case "$NPERMS" in (*[!0-9]*) echo "ERROR: --n-perms must be an integer" >&2; exit 2 ;; esac

# filesystem-safe tag: 0.01 -> 0p01
TAG="${MINSIG//./p}"
DERIVED_CONFIG="$REPO/workflow/config/config_minsig${TAG}.generated.yaml"

python3 - "$BASE_CONFIG" "$DERIVED_CONFIG" "$MINSIG" "$NPERMS" << 'PY'
import sys, yaml
base_path, out_path, minsig, nperms = sys.argv[1:5]
with open(base_path) as fh:
    cfg = yaml.safe_load(fh)
base_out = cfg.get("outdir", "results")
tag = minsig.replace(".", "p")
cfg["outdir"] = "%s_minsig%s" % (base_out, tag)
cfg["min_signal"] = float(minsig)
# keep the two min_signal knobs consistent (fixed-bin path uses min_signal;
# set adaptive too so a stray adaptive run cannot use a different threshold)
cfg["adaptive_min_signal"] = float(minsig)
cfg["n_perms"] = int(nperms)          # scout default 10; --n-perms 100 to publish
# hold everything else at production defaults so min_signal is the ONLY axis
cfg["cohort_reference"] = False
cfg["normalize"] = cfg.get("normalize", "")
header = ("# AUTO-GENERATED by run_cluster_minsig.sh from %s.\n"
          "# Differs from the base config ONLY in: outdir, min_signal, n_perms.\n" % base_path)
with open(out_path, "w") as fh:
    fh.write(header); yaml.safe_dump(cfg, fh, default_flow_style=False, sort_keys=False)
b = yaml.safe_load(open(base_path))
print("  base outdir  : %s" % base_out)
print("  minsig outdir: %s" % cfg["outdir"])
print("  min_signal   : %s (base was %s)" % (cfg["min_signal"], b.get("min_signal")))
print("  n_perms      : %s (base was %s)" % (cfg["n_perms"], b.get("n_perms")))
PY

CONFIG="$DERIVED_CONFIG"
OUT=$(python3 -c "import yaml;print(yaml.safe_load(open('$CONFIG'))['outdir'])")
echo "== min_signal run -> $OUT =="; echo

echo "== Preflight =="
python3 "$REPO/workflow/preflight.py" --configfile "$CONFIG" --core-only
echo

# p-value layers needed for BOTH the call-set comparison and the calibration
# (the calibration is the decisive readout for this scout).
SM_TARGETS=("$REPO/workflow/$OUT/pvalue.done"
            "$REPO/workflow/$OUT/pvalue_samples.done"
            "$REPO/workflow/$OUT/calibration/calibration_summary.tsv")
[ "$FULL" = "1" ] && SM_TARGETS=()

echo "== Dry run =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" -n "${SM_TARGETS[@]}"
if [ "$DRY" = "1" ]; then echo; echo "Dry run only."; exit 0; fi

echo; echo "== Submitting to SLURM =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" \
  --rerun-triggers mtime params \
  --profile "$PROFILE" "${SM_TARGETS[@]}"

echo; echo "Done -> workflow/$OUT/."
echo
echo "DECISIVE READOUT -- calibration (does it stay at 0 BH-significant?):"
echo "  cat workflow/$OUT/calibration/calibration_summary.tsv"
echo "  # compare BH-significant column against workflow/results (which is 0 in all five)"
echo
echo "SECONDARY -- do the significant regions survive? (q-values will shift"
echo "because the BH denominator changes; check the SIGNIFICANT REGIONS, not exact q):"
echo "  # regenerate/inspect the regional enrichment for workflow/$OUT and compare"
echo "  # the significant Tcrb/Igh regions against the production set."
