#!/usr/bin/env bash
#
# run_cluster_quantile_normalized.sh -- run the BEARING workflow with per-track
# quantile normalization turned ON, writing to a SEPARATE results folder so the
# default (un-normalized) run is left untouched and the two can be compared
# side by side.
#
# Rationale: each sample's KL is scored against a fixed reference Q. When a
# sample's marginal track distribution diverges from that reference (e.g. a
# low-dynamic-range ULI ChIP track, or a different assay/cell type), its
# per-sample null inflates. Quantile-normalizing every track to a common
# reference distribution removes that structural divergence. Running both lets
# us show whether BEARING's results -- especially the differential calls -- are
# robust to normalization, or whether quantile normalization is required for
# reliable per-sample significance. Either outcome is worth reporting.
#
#   bash workflow/run_cluster_quantile_normalized.sh             # full pipeline
#   bash workflow/run_cluster_quantile_normalized.sh --core-only # no Hi-C
#   bash workflow/run_cluster_quantile_normalized.sh --dry       # dry run only
#
# This is the quantile-normalized twin of run_cluster.sh. It derives its config
# from the live base config at launch time (overriding ONLY outdir and the
# normalize flag), so it can never drift from the base settings. Run from the
# same directory you would launch the default run. Requires the `bearing`
# conda env active. ASCII-only.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BASE_CONFIG="$REPO/workflow/config/config.yaml"
PROFILE="$REPO/workflow/profiles/slurm"

# Quantile-normalization mode and the separate results folder. We use the
# COHORT-WIDE per-track reference (cohort_reference: true), which equalizes
# between-sample dynamic range for the same assay -- the axis that fixes the
# per-sample null inflation. The Snakefile builds the cohort reference and
# passes --normalize-method cohort-quantile to every score job.
QNORM_SUFFIX="_qnorm"

CORE_ONLY=0
DRY=0
for a in "$@"; do
  case "$a" in
    --core-only) CORE_ONLY=1 ;;
    --dry)       DRY=1 ;;
    *) echo "unknown arg: $a" >&2; exit 2 ;;
  esac
done

# ---- derive the quantile-normalized config from the live base config --------
# Override only `outdir` (so outputs land in <base_outdir><suffix>) and turn on
# `cohort_reference` (cohort-wide per-track normalization). Everything else is
# inherited, so the two runs differ ONLY in normalization.
DERIVED_CONFIG="$REPO/workflow/config/config${QNORM_SUFFIX}.generated.yaml"
python3 - "$BASE_CONFIG" "$DERIVED_CONFIG" "$QNORM_SUFFIX" << 'PY'
import sys, yaml
base_path, out_path, suffix = sys.argv[1:4]
with open(base_path) as fh:
    cfg = yaml.safe_load(fh)
base_out = cfg.get("outdir", "results")
cfg["outdir"] = "%s%s" % (base_out, suffix)
cfg["cohort_reference"] = True
header = ("# AUTO-GENERATED by run_cluster_quantile_normalized.sh from %s.\n"
          "# Do not edit by hand; it is regenerated on every launch.\n"
          "# Differs from the base config ONLY in: outdir, cohort_reference.\n"
          % base_path)
with open(out_path, "w") as fh:
    fh.write(header)
    yaml.safe_dump(cfg, fh, default_flow_style=False, sort_keys=False)
print("  base outdir : %s" % base_out)
print("  qnorm outdir: %s" % cfg["outdir"])
print("  cohort_reference: %s (cohort-wide per-track normalization)" % cfg["cohort_reference"])
PY

CONFIG="$DERIVED_CONFIG"
OUT=$(python3 -c "import yaml;print(yaml.safe_load(open('$CONFIG'))['outdir'])")
echo "== Quantile-normalized run -> $OUT =="
echo

echo "== Preflight: checking every input file exists =="
PF_ARGS=(--configfile "$CONFIG")
[ "$CORE_ONLY" = "1" ] && PF_ARGS+=(--core-only)
python3 "$REPO/workflow/preflight.py" "${PF_ARGS[@]}"
echo

echo "== Snakemake dry run (validate DAG) =="
SM_TARGETS=()
if [ "$CORE_ONLY" = "1" ]; then
  SM_TARGETS=("$REPO/workflow/$OUT/pvalue.done"
              "$REPO/workflow/$OUT/pvalue_samples.done"
              "$REPO/workflow/$OUT/region_qc.done")
fi
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" -n "${SM_TARGETS[@]}"

if [ "$DRY" = "1" ]; then
  echo; echo "Dry run only (--dry). Not submitting."
  exit 0
fi

echo
echo "== Submitting to SLURM (one sbatch job per rule, via the slurm profile) =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" \
  --profile "$PROFILE" "${SM_TARGETS[@]}"

echo
echo "Done. Quantile-normalized outputs are in workflow/$OUT/."
echo "Compare against the default run, e.g.:"
echo "  diff <(sort workflow/results/regional/significant_bins_summary.tsv) \\"
echo "       <(sort workflow/$OUT/regional/significant_bins_summary.tsv)"
