#!/usr/bin/env bash
#
# run_cluster_quantile_normalized.sh -- run the BEARING workflow with per-track
# quantile normalization turned ON, writing to a SEPARATE results folder so the
# default (un-normalized) run is left untouched and the two can be compared
# side by side.
#
# Rationale: BEARING forms each bin's composition P(b,.) from the raw per-track
# signal, so a track with a much larger dynamic range can dominate the
# composition (and thus the KL) regardless of its biological relevance.
# Within-sample per-track quantile normalization equalizes each track's nonzero
# value distribution before P is formed. Running both the default (un-normalized)
# and the normalized version lets us show whether BEARING's results -- especially
# the differential calls and their direction -- are robust to track
# normalization. Either outcome is worth reporting.
#
#   bash workflow/run_cluster_quantile_normalized.sh             # full pipeline
#   bash workflow/run_cluster_quantile_normalized.sh --core-only # no Hi-C
#   bash workflow/run_cluster_quantile_normalized.sh --dry       # dry run only
#
# This is the quantile-normalized twin of run_cluster.sh. It derives its config
# from the live base config at launch time (overriding ONLY outdir and the
# normalize flag), so it can never drift from the base settings. Run from the
# same directory you would launch the default run. Requires the `bearing`
# conda env active. ASCII-only.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BASE_CONFIG="$REPO/workflow/config/config.yaml"
PROFILE="$REPO/workflow/profiles/slurm"

# Per-track quantile-normalization mode and the separate results folder. We use
# WITHIN-SAMPLE per-track quantile normalization via the `normalize` config knob
# (--normalize-tracks --normalize-method nonzero-quantile), a direct, verifiable
# code path (normalize_signal_matrix -> nonzero_quantile_normalize_columns).
# NOTE: this deliberately does NOT use cohort_reference, which is a separate
# (cohort-wide reference) path that in prior runs left the KL unchanged. This
# launcher equalizes each track's nonzero dynamic range so no single
# high-dynamic-range track dominates the per-bin composition.
QNORM_SUFFIX="_qnorm"

CORE_ONLY=0
DRY=0
NPERMS=10
for a in "$@"; do
  case "$a" in
    --core-only) CORE_ONLY=1 ;;
    --dry)       DRY=1 ;;
    --n-perms=*) NPERMS="${a#*=}" ;;
    *) echo "unknown arg: $a" >&2; exit 2 ;;
  esac
done
case "$NPERMS" in (*[!0-9]*) echo "ERROR: --n-perms must be an integer (use --n-perms=N)" >&2; exit 2 ;; esac

# ---- derive the quantile-normalized config from the live base config --------
# Override only `outdir` (so outputs land in <base_outdir><suffix>), the
# `normalize` knob (turn on within-sample per-track quantile normalization),
# and n_perms (pin this arm's depth, default 10).
# Everything else is inherited, so the runs differ ONLY in normalization + depth.
DERIVED_CONFIG="$REPO/workflow/config/config${QNORM_SUFFIX}.generated.yaml"
python3 - "$BASE_CONFIG" "$DERIVED_CONFIG" "$QNORM_SUFFIX" "$NPERMS" << 'PY'
import sys, yaml
base_path, out_path, suffix, nperms = sys.argv[1:5]
with open(base_path) as fh:
    cfg = yaml.safe_load(fh)
base_out = cfg.get("outdir", "results")
cfg["outdir"] = "%s%s" % (base_out, suffix)
cfg["normalize"] = "--normalize-tracks --normalize-method nonzero-quantile"
cfg["cohort_reference"] = False  # use within-sample normalization, not cohort ref
cfg["n_perms"] = int(nperms)
header = ("# AUTO-GENERATED by run_cluster_quantile_normalized.sh from %s.\n"
          "# Do not edit by hand; it is regenerated on every launch.\n"
          "# Differs from the base config ONLY in: outdir, normalize, n_perms.\n"
          % base_path)
with open(out_path, "w") as fh:
    fh.write(header)
    yaml.safe_dump(cfg, fh, default_flow_style=False, sort_keys=False)
print("  base outdir : %s" % base_out)
print("  qnorm outdir: %s" % cfg["outdir"])
print("  normalize   : %s" % cfg["normalize"])
print("  n_perms     : %s (base was %s)" % (cfg["n_perms"], yaml.safe_load(open(base_path)).get("n_perms")))
PY

CONFIG="$DERIVED_CONFIG"
OUT=$(python3 -c "import yaml;print(yaml.safe_load(open('$CONFIG'))['outdir'])")
echo "== Quantile-normalized run -> $OUT =="
echo

echo "== Preflight: checking every input file exists =="
PF_ARGS=(--configfile "$CONFIG")
[ "$CORE_ONLY" = "1" ] && PF_ARGS+=(--core-only)
python3 "$REPO/workflow/preflight.py" "${PF_ARGS[@]}"
echo

echo "== Snakemake dry run (validate DAG) =="
SM_TARGETS=()
if [ "$CORE_ONLY" = "1" ]; then
  SM_TARGETS=("$REPO/workflow/$OUT/pvalue.done"
              "$REPO/workflow/$OUT/pvalue_samples.done"
              "$REPO/workflow/$OUT/regional/cbe_point_query.tsv"
              "$REPO/workflow/$OUT/regional/cbe_track_changes.tsv"
              "$REPO/workflow/$OUT/regional/agr_track_changes.tsv"
              "$REPO/workflow/$OUT/region_qc.done")
fi
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" -n "${SM_TARGETS[@]}"

if [ "$DRY" = "1" ]; then
  echo; echo "Dry run only (--dry). Not submitting."
  exit 0
fi

echo
echo "== Submitting to SLURM (one sbatch job per rule, via the slurm profile) =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" \
  --profile "$PROFILE" "${SM_TARGETS[@]}"

echo
echo "Done. Quantile-normalized outputs are in workflow/$OUT/."
echo "Compare against the default run, e.g.:"
echo "  diff <(sort workflow/results/regional/significant_bins_summary.tsv) \\"
echo "       <(sort workflow/$OUT/regional/significant_bins_summary.tsv)"
