#!/usr/bin/env bash
#
# run_cluster_jsd.sh -- run the pipeline with the bounded Jensen-Shannon score
# (--score-method jsd) into a separate results folder, as a third robustness
# axis alongside the default-vs-qnorm normalization comparison.
#
# Derives its config from the live base config, overriding ONLY outdir + the
# score_method knob (normalization stays whatever the base config uses; by
# default that is OFF, matching the production default run). The observed scores
# AND the permutation null are both computed with JSD, so the null matches.
#
#   bash workflow/run_cluster_jsd.sh            # core path -> results_jsd/
#   bash workflow/run_cluster_jsd.sh --full     # full pipeline
#   bash workflow/run_cluster_jsd.sh --dry      # dry run only
#   bash workflow/run_cluster_jsd.sh --n-perms 10  # pin perm depth (default 10)
#
# Compare against the default (KL) run with compare_default_vs_qnorm.py:
#   python compare_default_vs_qnorm.py \
#     --default-dir workflow/results/pvalue \
#     --qnorm-dir   workflow/results_jsd/pvalue
# (here 'qnorm-dir' is the JSD run; the Jaccard/rho it reports is the
#  KL-vs-JSD scoring-method concordance, not a normalization effect.)
# ASCII-only.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BASE_CONFIG="$REPO/workflow/config/config.yaml"
PROFILE="$REPO/workflow/profiles/slurm"

NPERMS=10
FULL=0
DRY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --n-perms) NPERMS="$2"; shift 2 ;;
    --n-perms=*) NPERMS="${1#*=}"; shift ;;
    --full) FULL=1; shift ;;
    --dry)  DRY=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
case "$NPERMS" in (*[!0-9]*) echo "ERROR: --n-perms must be an integer" >&2; exit 2 ;; esac

DERIVED_CONFIG="$REPO/workflow/config/config_jsd.generated.yaml"
python3 - "$BASE_CONFIG" "$DERIVED_CONFIG" "$NPERMS" << 'PY'
import sys, yaml
base_path, out_path, nperms = sys.argv[1:4]
with open(base_path) as fh:
    cfg = yaml.safe_load(fh)
base_out = cfg.get("outdir", "results")
cfg["outdir"] = "%s_jsd" % base_out
cfg["score_method"] = "jsd"
# Pin this arm's permutation depth independently of the production base config
# (which may sit at the n_perms=100 production value); robustness arms default
# to 10 unless --n-perms overrides.
cfg["n_perms"] = int(nperms)
header = ("# AUTO-GENERATED by run_cluster_jsd.sh from %s.\n"
          "# Differs from the base config ONLY in: outdir, score_method=jsd, n_perms.\n" % base_path)
with open(out_path, "w") as fh:
    fh.write(header); yaml.safe_dump(cfg, fh, default_flow_style=False, sort_keys=False)
print("  base outdir  : %s" % base_out)
print("  jsd outdir   : %s" % cfg["outdir"])
print("  score_method : jsd")
print("  n_perms      : %s (base was %s)" % (cfg["n_perms"], yaml.safe_load(open(base_path)).get("n_perms")))
PY

CONFIG="$DERIVED_CONFIG"
OUT=$(python3 -c "import yaml;print(yaml.safe_load(open('$CONFIG'))['outdir'])")
echo "== JSD run -> $OUT =="; echo

echo "== Preflight =="
python3 "$REPO/workflow/preflight.py" --configfile "$CONFIG" --core-only
echo

SM_TARGETS=("$REPO/workflow/$OUT/pvalue.done"
            "$REPO/workflow/$OUT/pvalue_samples.done"
            "$REPO/workflow/$OUT/regional/cbe_point_query.tsv"
            "$REPO/workflow/$OUT/regional/cbe_track_changes.tsv"
            "$REPO/workflow/$OUT/regional/agr_track_changes.tsv")
[ "$FULL" = "1" ] && SM_TARGETS=()

echo "== Dry run =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" -n "${SM_TARGETS[@]}"
if [ "$DRY" = "1" ]; then echo; echo "Dry run only."; exit 0; fi

echo; echo "== Submitting to SLURM =="
snakemake -s "$REPO/workflow/Snakefile" --configfile "$CONFIG" \
  --profile "$PROFILE" "${SM_TARGETS[@]}"

echo; echo "Done -> workflow/$OUT/. Compare against the default (KL) run:"
echo "  python compare_default_vs_qnorm.py \\"
echo "    --default-dir workflow/results/pvalue \\"
echo "    --qnorm-dir   workflow/$OUT/pvalue"
