# =====================================================================
# Snakefile -- depth-matched MCC adaptive-vs-uniform binning analysis
#
# RUN FROM THE REPO ROOT (all paths resolve from there):
#   snakemake -n -s mcc/Snakefile --configfile mcc/config.yaml
#   snakemake    -s mcc/Snakefile --configfile mcc/config.yaml --cores 8
#
# Prereqs (built once, on the cluster, before launching):
#   - workflow/results_v1/pvalue/diff_*.neglog10p.bw   (../workflow + config_v1)
#   - seg_v1_chr6_real.bed                              (build_adaptive_segmentation)
#   - mcc_grid_benchmark/pair_counts_v1.tsv             (run_mcc_grid_benchmark)
#   - anchors_v1.bed = cat AgRgenes_mm10_s.bed cbe_mm10.bed
# ASCII only.
# =====================================================================
import os

configfile: "mcc/config.yaml"

S          = config["scriptdir"]
CHROM      = config["chrom"]
ANCHORS    = config["anchors"]
CBE        = config["cbe"]
GENES      = config["genes"]
BES_DIR    = config["bes_dir"]
SEG        = config["segmentation"]
SEG_MASK   = SEG.replace(".bed", ".cbemask.bed")
SHEET      = config["sheet"]
CATS       = config["cats"]
COMP       = config["comparisons_file"]
COOLDIR    = config["cool_dir"]
BAM        = config["bam_dir"]
PAIRCOUNTS = "mcc_grid_benchmark/pair_counts_v1.tsv"
PAIRS_OK   = "capture_cools.downsample_done"
RES        = config["res"]
WINDOWS    = config["windows"]
STD        = config["std_binsize"]
MIND       = config["min_distance"]
MAXD       = config["max_distance"]
SHIFT      = config["min_shift"]

PAIRS = ["%s_vs_%s" % (a, b) for a, b in config["comparisons"]]


def bes_bw(pair):
    return os.path.join(BES_DIR, "diff_%s.neglog10p.bw" % pair)


rule all:
    input:
        "mcc_grid_benchmark/grid_benchmark_native.tsv",
        "mcc_grid_benchmark/grid_benchmark_floored.tsv",
        "mcc_grid_benchmark/grid_benchmark_native_cbemask.tsv",
        expand("mcc_grid_benchmark/partial_{pair}_{win}.txt",
               pair=PAIRS, win=list(WINDOWS)),
        expand("figures/fig_1d_vs_3d_{pair}.pdf", pair=PAIRS),
        expand("figures/mcc_bearing_{pair}.pdf", pair=PAIRS),
        "mcc_grid_benchmark/feature_geometry.txt",
        "SIGN_MAP.tsv",


rule downsampled_cools:
    output:
        touch(PAIRS_OK)
    shell:
        "bash {S}/build_capture_cools.sh --downsample --res {RES}"


rule cbe_mask_grid:
    input:
        seg = SEG, cbe = CBE
    output:
        SEG_MASK
    params:
        pad = config["cbe_pad"]
    shell:
        "awk 'BEGIN{{OFS=\"\\t\"}}{{print $1,($2>{params.pad}?$2-{params.pad}:0),"
        "$3+{params.pad}}}' {input.cbe} > .cbe_pad.bed && "
        "bedtools intersect -v -a {input.seg} -b .cbe_pad.bed > {output}"


rule benchmark_native:
    input:
        seg = SEG, counts = PAIRCOUNTS, anchors = ANCHORS, comp = COMP
    output:
        tsv = "mcc_grid_benchmark/grid_benchmark_native.tsv",
        dumps = expand("mcc_grid_benchmark/binwise_{pair}.tsv", pair=PAIRS)
    shell:
        "python {S}/benchmark_grid_vs_standard.py --superbins {input.seg} "
        "--counts {input.counts} --bam-dir {BAM} --comparisons {input.comp} "
        "--annot {input.anchors} --std-binsize {STD} --min-distance {MIND} "
        "--max-distance {MAXD} --min-shift {SHIFT} "
        "--out {output.tsv} --dump-bins mcc_grid_benchmark/binwise"


rule benchmark_floored:
    input:
        seg = SEG, counts = PAIRCOUNTS, anchors = ANCHORS, comp = COMP
    output:
        "mcc_grid_benchmark/grid_benchmark_floored.tsv"
    shell:
        "python {S}/build_superbin_grid.py --seg {input.seg} "
        "--min-width 1000 --out-bed superbins_v1r_1000.bed && "
        "python {S}/benchmark_grid_vs_standard.py --superbins superbins_v1r_1000.bed "
        "--counts {input.counts} --bam-dir {BAM} --comparisons {input.comp} "
        "--annot {input.anchors} --std-binsize {STD} --min-distance {MIND} "
        "--max-distance {MAXD} --min-shift {SHIFT} "
        "--out {output} --dump-bins mcc_grid_benchmark/binwise_floored"


rule benchmark_cbemask:
    input:
        seg = SEG_MASK, counts = PAIRCOUNTS, anchors = ANCHORS, comp = COMP
    output:
        tsv = "mcc_grid_benchmark/grid_benchmark_native_cbemask.tsv",
        dumps = expand("mcc_grid_benchmark/binwise_cbemask_{pair}.tsv", pair=PAIRS)
    shell:
        "python {S}/benchmark_grid_vs_standard.py --superbins {input.seg} "
        "--counts {input.counts} --bam-dir {BAM} --comparisons {input.comp} "
        "--annot {input.anchors} --std-binsize {STD} --min-distance {MIND} "
        "--max-distance {MAXD} --min-shift {SHIFT} "
        "--out {output.tsv} --dump-bins mcc_grid_benchmark/binwise_cbemask"


rule partial:
    input:
        "mcc_grid_benchmark/binwise_{pair}.tsv"
    output:
        "mcc_grid_benchmark/partial_{pair}_{win}.txt"
    params:
        region = lambda wc: WINDOWS[wc.win]
    shell:
        "python {S}/partial_corr.py {input} --region {params.region} > {output}"


rule sign_map:
    input:
        expand("mcc_grid_benchmark/partial_{pair}_{win}.txt",
               pair=PAIRS, win=list(WINDOWS))
    output:
        "SIGN_MAP.tsv"
    run:
        with open(output[0], "w") as o:
            o.write("comparison\twindow\trho_raw\trho_depth\trho_depth_width\tpremise\n")
            for f in input:
                base = os.path.basename(f)[len("partial_"):-len(".txt")]
                pair, win = base.rsplit("_", 1)
                v = {}
                for line in open(f):
                    if line.startswith("rho_raw"):
                        v["raw"] = line.split(":")[1].split()[0]
                    elif line.startswith("rho | depth "):
                        v["d"] = line.split(":")[1].split()[0]
                    elif line.startswith("rho | depth,width"):
                        v["dw"] = line.split(":")[1].split()[0]
                    elif line.startswith("[premise]"):
                        v["prem"] = line.split("=")[1].split()[0]
                o.write("%s\t%s\t%s\t%s\t%s\t%s\n" % (pair, win,
                        v.get("raw", "NA"), v.get("d", "NA"),
                        v.get("dw", "NA"), v.get("prem", "NA")))


rule fig_1d_vs_3d:
    input:
        dump = "mcc_grid_benchmark/binwise_{pair}.tsv", cbe = CBE
    output:
        "figures/fig_1d_vs_3d_{pair}.pdf"
    params:
        region = config["fig_region"], hl = config["v1_promoter"]
    shell:
        "python {S}/plot_1d_vs_3d.py --dump {input.dump} --region {params.region} "
        "--features {input.cbe} --highlight {params.hl} "
        "--title 'DN vs {wildcards.pair} -- Tcrb MCC' --out {output}"


rule mcc_ini:
    input:
        ok = PAIRS_OK, bes = lambda wc: bes_bw(wc.pair),
        genes = GENES, cbe = CBE, sheet = SHEET, cats = CATS
    output:
        "figures/tracks_{pair}.ini"
    params:
        a = lambda wc: wc.pair.split("_vs_")[0],
        b = lambda wc: wc.pair.split("_vs_")[1],
        region = config["fig_region"], res = RES, cooldir = COOLDIR
    shell:
        "python {S}/make_mcc_bearing_ini.py --sheet {input.sheet} "
        "--cats {input.cats} --bes {input.bes} "
        "--cools {params.a}:{params.cooldir}/merged_capture_{params.a}_bs_{params.res}.cool,"
        "{params.b}:{params.cooldir}/merged_capture_{params.b}_bs_{params.res}.cool "
        "--panel-condition {params.b} --overlay-condition {params.a} "
        "--genes {input.genes} --features {input.cbe} "
        "--region {params.region} --out-ini {output}"


rule pygenometracks:
    input:
        "figures/tracks_{pair}.ini"
    output:
        "figures/mcc_bearing_{pair}.pdf"
    params:
        region = config["fig_region"]
    shell:
        "pyGenomeTracks --tracks {input} --region {params.region} -o {output}"


rule geometry:
    input:
        seg = SEG, anchors = ANCHORS
    output:
        "mcc_grid_benchmark/feature_geometry.txt"
    params:
        region = WINDOWS["full"]
    shell:
        "python {S}/superbin_feature_overlap.py --superbins {input.seg} "
        "--features {input.anchors} --region {params.region} > {output}"
